"""Automate downloading and processing PubMed."""

from .api import (
    AbstractText,
    Article,
    Journal,
    ensure_baselines,
    ensure_updates,
    iterate_ensure_articles,
    iterate_ensure_baselines,
    iterate_ensure_updates,
    iterate_process_articles,
    iterate_process_baselines,
    iterate_process_updates,
    process_articles,
    process_baselines,
    process_updates,
)
from .catalog import (
    CatalogRecord,
    ensure_catalog_provider_links,
    ensure_catfile_catalog,
    ensure_j_entrez,
    ensure_j_medline,
    ensure_journal_overview,
    ensure_serfile_catalog,
    get_catalog_to_publisher,
    get_journals,
    process_catalog,
    process_journal_overview,
)
from .client import (
    count_search_results,
    get_abstracts,
    get_abstracts_dict,
    get_articles,
    get_articles_dict,
    get_titles,
    get_titles_dict,
    search,
)
from .utils import ISSN, Author, Heading, Qualifier

__all__ = [
    "ISSN",
    "AbstractText",
    "Article",
    "Author",
    "CatalogRecord",
    "Heading",
    "Journal",
    "Qualifier",
    "count_search_results",
    "ensure_baselines",
    "ensure_catalog_provider_links",
    "ensure_catfile_catalog",
    "ensure_j_entrez",
    "ensure_j_medline",
    "ensure_journal_overview",
    "ensure_serfile_catalog",
    "ensure_updates",
    "get_abstracts",
    "get_abstracts_dict",
    "get_articles",
    "get_articles_dict",
    "get_catalog_to_publisher",
    "get_journals",
    "get_titles",
    "get_titles_dict",
    "iterate_ensure_articles",
    "iterate_ensure_baselines",
    "iterate_ensure_updates",
    "iterate_process_articles",
    "iterate_process_baselines",
    "iterate_process_updates",
    "process_articles",
    "process_baselines",
    "process_catalog",
    "process_journal_overview",
    "process_updates",
    "search",
]
