"""Calculate stas."""

from collections import Counter

import click
from tabulate import tabulate

from pubmed_downloader import iterate_process_articles

RELABELLING = {
    "ASTRACT": "ABSTRACT",
    "ABSTRACT": "ABSTRACT",
    "Abstract": "ABSTRACT",
    #
    "Background": "BACKGROUND",
    "BACKGROUND/AIMS": "BACKGROUND",
    "BACKGROUND & AIM": "BACKGROUND",
    "BACKGROUND AND AIMS": "BACKGROUND",
    "BACKGROUND AND PURPOSE": "BACKGROUND",
    "BACKGROUND & OBJECTIVE": "BACKGROUND",
    "BACKGROUND AND OBJECTIVE": "BACKGROUND",
    "BACKGROUND AND AIM": "BACKGROUND",
    "MOTIVATION": "BACKGROUND",
    "Aims": "BACKGROUND",
    "Motivation": "BACKGROUND",
    "BACKGROUND/OBJECTIVES": "BACKGROUND",
    "BACKGROUND/OBJECTIVE": "BACKGROUND",
    #
    "Objective": "OBJECTIVES",
    "OBJECTIVE": "OBJECTIVES",
    "OBJECTIVES": "OBJECTIVES",
    #
    "Introduction": "INTRODUCTION",
    "INTRODUCTION AND IMPORTANCE": "INTRODUCTION",
    "BACKGROUND/INTRODUCTION": "INTRODUCTION",
    "INTRODUCTION/OBJECTIVES": "INTRODUCTION",
    "INTRODUCTION AND OBJECTIVES": "INTRODUCTION",
    #
    "METHOD": "MATERIALS AND METHODS",
    "Methods": "MATERIALS AND METHODS",
    "RESEARCH DESIGN AND METHODS": "MATERIALS AND METHODS",
    "PATIENTS AND METHODS": "MATERIALS AND METHODS",
    "MATERIAL AND METHODS": "MATERIALS AND METHODS",
    "MATERIAL AND METHOD": "MATERIALS AND METHODS",
    "MATERIALS & METHODS": "MATERIALS AND METHODS",
    "METHODS AND STUDY DESIGN": "MATERIALS AND METHODS",
    "INVESTIGATION AND METHODOLOGIES": "MATERIALS AND METHODS",
    "METHODOLOGY": "MATERIALS AND METHODS",
    "EXPERIMENTAL DESIGN": "MATERIALS AND METHODS",
    "METHOD AND ANALYSIS": "MATERIALS AND METHODS",
    "STUDY DESIGN": "MATERIALS AND METHODS",
    "Design, Setting, and Participants": "MATERIALS AND METHODS",
    "STUDY DESIGN AND METHODS": "MATERIALS AND METHODS",
    "MATERIALS AND METHOD": "MATERIALS AND METHODS",
    "METHODS AND MATERIALS": "MATERIALS AND METHODS",
    "Method": "MATERIALS AND METHODS",
    "Methodology": "MATERIALS AND METHODS",
    "Materials and Methods": "MATERIALS AND METHODS",
    "MATERIALS": "MATERIALS AND METHODS",
    "MATERLALS AND METHODS": "MATERIALS AND METHODS",
    "DESIGN/METHODOLOGY/APPROACH": "MATERIALS AND METHODS",
    #
    "METHODS AND RESULTS": "METHODS AND RESULTS",
    "METHODS AND ANALYSIS": "METHODS AND RESULTS",
    "APPROACH AND RESULTS": "METHODS AND RESULTS",
    "METHODS AND FINDINGS": "METHODS AND RESULTS",
    #
    "RESULT": "RESULTS",
    "MEASUREMENTS AND MAIN RESULTS": "RESULTS",
    "MAIN OUTCOME MEASURES": "RESULTS",
    "Main Outcome and Measures": "RESULTS",
    "MAIN OUTCOMES AND MEASURES": "RESULTS",
    "Results": "RESULTS",
    "MAIN OUTCOME MEASURE": "RESULTS",
    "Design": "RESULTS",
    "THE RESULTS": "RESULTS",
    "MAIN RESULTS": "RESULTS",
    "Main Outcomes and Measures": "RESULTS",
    "FINDINGS": "RESULTS",
    "OUTCOMES": "RESULTS",
    "MAIN FINDINGS": "RESULTS",
    #
    "RESULTS AND DISCUSSION": "RESULTS AND DISCUSSION",
    "RESULTS AND LIMITATIONS": "RESULTS AND DISCUSSION",
    "KEY FINDINGS AND LIMITATIONS": "RESULTS AND DISCUSSION",
    #
    "DISCUSSION": "DISCUSSION",
    "Discussion": "DISCUSSION",
    "Interpretation": "DISCUSSION",
    #
    "DISCUSSION & CONCLUSION": "DISCUSSION AND CONCLUSION",
    "DISSCUSSION AND CONCLUSION": "DISCUSSION AND CONCLUSION",
    "DISCUSSION AND CONCLUSIONS": "DISCUSSION AND CONCLUSION",
    "DISCUSSION AND CONCLUSION": "DISCUSSION AND CONCLUSION",
    "LIMITATIONS": "DISCUSSION AND CONCLUSION",
    "Limitations": "DISCUSSION AND CONCLUSION",
    "Future work": "DISCUSSION AND CONCLUSION",
    "DISCUSSION/CONCLUSIONS": "DISCUSSION AND CONCLUSION",
    "DISCUSSION AND IMPLICATIONS": "DISCUSSION AND CONCLUSION",
    #
    "IN CONCLUSION": "CONCLUSION",
    "Conclusion": "CONCLUSION",
    "AUTHORS' CONCLUSIONS": "CONCLUSION",
    "Conclusions": "CONCLUSION",
    "CONCLUSION AND IMPLICATIONS": "CONCLUSION",
    "CONCLUSIONS": "CONCLUSION",
    "CONCLUSIONS AND IMPLICATIONS": "CONCLUSION",
    "Conclusions and Relevance": "CONCLUSION",
    "CONCLUSIONS AND RELEVANCE": "CONCLUSION",
    "CONCLUSIONS AND CLINICAL IMPLICATIONS": "CONCLUSION",
    #
    "FUNDING": "FUNDING",
    "Funding": "FUNDING",
    "FUNDINGS": "FUNDING",
}


def main() -> None:
    """Calculate stats."""
    label_counter: Counter[str] = Counter()
    category_counter: Counter[str] = Counter()

    n = 10_000_000
    n = 10_000
    for article, _ in zip(iterate_process_articles(), range(n), strict=False):
        for t in article.abstract:
            if t.label:
                label_counter[RELABELLING.get(t.label, t.label)] += 1
            if t.category:
                category_counter[t.category] += 1

    click.echo("Label Counter")
    click.echo(tabulate(label_counter.most_common()))

    click.echo("\nCategory Counter")
    click.echo(tabulate(category_counter.most_common()))


if __name__ == "__main__":
    main()
